[email_config]
sender_email = "reportsvisualizadorimg@gmail.com"
sender_password = "ckey bowx rmvv oeal"
recipient_email = "5e5c1fb5.topshop.com.br@br.teams.ms"
smtp_server = "smtp.gmail.com"
smtp_port = 587
